name: spdx-license-check

on: [pull_request,push]

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0
          MIT
          BSD-3-Clause
